"""Stage 2: extract per-window, per-sensor time- and frequency-domain
features (Sec 5.3) from the dataset generated by 01_generate_synthetic.py,
standardise them using healthy-only statistics, and verify the Sec 5.3
acceptance criteria (clean feature matrix, visible healthy/damaged
separation on at least one spectral feature).

Run from the repo root (after 01_generate_synthetic.py):
    python scripts/02_extract_features.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml
from sklearn.preprocessing import StandardScaler

from src.features.spectral import spectral_features
from src.features.windows import time_domain_features
from src.fem.geometry import generate_lattice_geometry

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "data" / "synthetic"
FIGURES_DIR = REPO_ROOT / "figures"

NON_FEATURE_COLUMNS = ("window_id", "sensor_idx", "sensor_node_id", "instance_id",
                        "damage_severity", "temperature_c")


def load_config() -> dict:
    with open(REPO_ROOT / "configs" / "default.yaml") as f:
        return yaml.safe_load(f)


def build_feature_table(windows: np.ndarray, labels: pd.DataFrame, sensor_node_ids: np.ndarray,
                         sampling_rate_hz: float, band_edges_hz: list) -> pd.DataFrame:
    """Compute time- and frequency-domain features for every (window,
    sensor) pair and lay them out as a long table, one row per pair.
    """
    time_feats = time_domain_features(windows)
    freq_feats = spectral_features(windows, sampling_rate_hz, band_edges_hz)
    all_feats = {**time_feats, **freq_feats}

    n_windows, n_sensors = windows.shape[0], windows.shape[1]
    table = pd.DataFrame({
        "window_id": np.repeat(np.arange(n_windows), n_sensors),
        "sensor_idx": np.tile(np.arange(n_sensors), n_windows),
        "sensor_node_id": np.tile(sensor_node_ids, n_windows),
    })
    table = table.merge(labels, on="window_id", how="left")
    for name, arr in all_feats.items():
        table[name] = arr.ravel()
    return table


def nearest_sensor_idx(geometry, sensor_node_ids: np.ndarray, damaged_element_nodes: np.ndarray) -> int:
    """Index (into `sensor_node_ids`) of the sensor closest in height to
    the damaged element's midpoint, i.e. the sensor most likely to see a
    local effect from a single damaged brace.
    """
    damage_height = geometry.nodes[damaged_element_nodes, 2].mean()
    sensor_heights = geometry.nodes[sensor_node_ids, 2]
    return int(np.argmin(np.abs(sensor_heights - damage_height)))


def check_separation(table: pd.DataFrame, feature_cols: list, nearest_node_id: int) -> str:
    """Verify Sec 5.3: healthy and damaged distributions are visibly
    separate on at least one spectral feature, at the sensor nearest the
    damage. Ranks every feature by effect size (Cohen's d) and returns the
    name of the most separated one.
    """
    at_sensor = table[table["sensor_node_id"] == nearest_node_id]
    healthy = at_sensor[at_sensor["damage_severity"] == 0.0]
    damaged = at_sensor[at_sensor["damage_severity"] == at_sensor["damage_severity"].max()]

    scores = {}
    for col in feature_cols:
        pooled_std = np.sqrt((healthy[col].var() + damaged[col].var()) / 2)
        scores[col] = abs(healthy[col].mean() - damaged[col].mean()) / pooled_std if pooled_std > 0 else 0.0

    ranked = sorted(scores.items(), key=lambda kv: kv[1], reverse=True)
    print(f"\nSeparation (Cohen's d, healthy vs full-severity damage) at sensor node {nearest_node_id}, "
          f"top 5 of {len(feature_cols)} features:")
    for name, score in ranked[:5]:
        print(f"  {name}: d={score:.2f}")

    best_feature, best_score = ranked[0]
    assert best_score > 0.5, (
        f"No feature separates healthy from damaged with at least a medium effect size "
        f"(best was {best_feature} at d={best_score:.2f})"
    )
    print(f"[OK] '{best_feature}' visibly separates healthy from damaged (Cohen's d={best_score:.2f})")
    return best_feature


def plot_separation(table: pd.DataFrame, feature: str, nearest_node_id: int) -> None:
    at_sensor = table[table["sensor_node_id"] == nearest_node_id]
    severities = sorted(at_sensor["damage_severity"].unique())

    fig, ax = plt.subplots(figsize=(6, 4))
    data = [at_sensor.loc[at_sensor["damage_severity"] == s, feature] for s in severities]
    labels_x = ["healthy" if s == 0.0 else f"d={s:.1f}" for s in severities]
    ax.boxplot(data, tick_labels=labels_x)
    ax.set_ylabel(feature)
    ax.set_title(f"'{feature}' at sensor node {nearest_node_id} (nearest to damage)\nby damage severity")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    FIGURES_DIR.mkdir(exist_ok=True)
    out_path = FIGURES_DIR / "day2_feature_separation.png"
    fig.savefig(out_path, dpi=150)
    print(f"Saved {out_path}")


def main() -> None:
    config = load_config()
    npz = np.load(DATA_DIR / "windows.npz")
    labels = pd.read_csv(DATA_DIR / "labels.csv")

    windows = npz["windows"]
    sensor_node_ids = npz["sensor_node_ids"]
    sampling_rate_hz = float(npz["sampling_rate_hz"])
    damaged_element_nodes = npz["damaged_element_nodes"]

    table = build_feature_table(
        windows, labels, sensor_node_ids, sampling_rate_hz, config["features"]["band_edges_hz"],
    )
    feature_cols = [c for c in table.columns if c not in NON_FEATURE_COLUMNS]
    print(f"Feature table: {table.shape[0]} rows (window x sensor), {len(feature_cols)} features")

    healthy_mask = table["damage_severity"] == 0.0
    scaler = StandardScaler().fit(table.loc[healthy_mask, feature_cols])
    scaled_table = table.copy()
    scaled_table[feature_cols] = scaler.transform(table[feature_cols])

    assert np.isfinite(table[feature_cols].to_numpy()).all(), "Raw feature matrix has NaN/inf"
    assert np.isfinite(scaled_table[feature_cols].to_numpy()).all(), "Scaled feature matrix has NaN/inf"
    print("[OK] Feature matrix has no NaN/inf (raw and healthy-scaled)")

    geometry = generate_lattice_geometry(config)
    nearest_idx = nearest_sensor_idx(geometry, sensor_node_ids, damaged_element_nodes)
    nearest_node_id = int(sensor_node_ids[nearest_idx])

    best_feature = check_separation(table, feature_cols, nearest_node_id)
    plot_separation(table, best_feature, nearest_node_id)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    table.to_csv(DATA_DIR / "features_raw.csv", index=False)
    scaled_table.to_csv(DATA_DIR / "features_scaled.csv", index=False)
    print(f"Saved {DATA_DIR / 'features_raw.csv'} and {DATA_DIR / 'features_scaled.csv'}")


if __name__ == "__main__":
    main()
